# Generated by Django 4.1.5 on 2023-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
