# Generated by Django 4.1.5 on 2023-03-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0002_alter_interim_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='interim',
            field=models.ManyToManyField(related_name='Employeurs', to='plateforme.interim'),
        ),
        migrations.AddField(
            model_name='interim',
            name='Employeur',
            field=models.ManyToManyField(related_name='Interim', to='plateforme.employeur'),
        ),
    ]
