# Generated by Django 4.1.5 on 2023-03-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0002_ali'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ali',
        ),
    ]
