# Generated by Django 4.1.5 on 2023-03-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0003_delete_ali'),
    ]

    operations = [
        migrations.AddField(
            model_name='interimuser',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='interimuser',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
