# Generated by Django 4.1.5 on 2023-03-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
