# Generated by Django 4.1.5 on 2023-03-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0006_customuser_adresse_customuser_nom_customuser_societe_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='EmpUser',
        ),
    ]
