# Generated by Django 4.1.5 on 2023-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0007_rename_customuser_empuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='domaine',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
