# Generated by Django 4.1.5 on 2023-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('plateforme', '0009_creuser_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreUser',
            new_name='AddUser',
        ),
    ]
