# Generated by Django 4.1.5 on 2023-03-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0013_employer_worker_customuser_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Employeur',
        ),
    ]
